### ISSUE TITLE
cmptxtrender does not show names of SMP characters

### ISSUE THREAD

**Issue by devosb** [silnrsi/palaso-python#4]
The output of `cmptxtrender` shows the input text of the string being tested. It does this by showing the glyph names of the input characters (as opposed to the USV of the characters) in a column called _Original_ when called from `smith test` or `smith xtest`

If an input character is a non-BMP character, then `.notdef` is shown. The glyph name should be shown instead. The correct glyph names are shown in the rendered output.

You can see examples of this in the `xtest` output for [Narnoor](https://github.com/silnrsi/font-narnoor) at https://build.palaso.org/viewType.html?buildTypeId=Fonts_Narnoor Look for `.html` files in the folder `tests/xtest` in a built artefact.

I suspect the string `.notdef` is coming from https://github.com/silnrsi/palaso-python/blob/master/scripts/font/cmptxtrender#L46 or maybe the next line. Since BMP characters work correctly, I wonder if there is a bug in binary/text strings related to how SMP characters are stored. This issue happens on both Python 2 and 3.

**Comment by bobh0303** [comment]
Thanks!
